### PR TITLE
Enable osx-arm64 platform

### PR DESCRIPTION
**Pull request by andrey-khropov**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by andrey-khropov** [comment]
@conda-forge-admin, please rerender

**Comment by andrey-khropov** [comment]
@conda-forge-admin, please rerender

**Comment by andrey-khropov** [comment]
@conda-forge-admin, please rerender

**Comment by mfansler** [comment]
Thanks for proposing this! However, it is preferable that OSX ARM64 migrations go through `conda-forge-pinning-feedstock` so that their status can be tracked and the current standard transformation applied as a starting point. Please make a PR on https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt adding the `r-catboost` package.

**Comment by andrey-khropov** [comment]
> Thanks for proposing this! However, it is preferable that OSX ARM64 migrations go through `conda-forge-pinning-feedstock` so that their status can be tracked and the current standard transformation applied as a starting point. Please make a PR on https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt adding the `r-catboost` package.

Ok, https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4447. But this change in this PR https://github.com/conda-forge/r-catboost-feedstock/pull/69/files#diff-d7075654874cb08007a21aaab3ecd4b3453a9087e7505d034d548b8938b599bc is still needed in order for the build to succeed. I don't think the mirgration bot is smart enough to figure it out. Is the idea that I'll have to push additional commits to robot's migration PR?

**Comment by mfansler** [comment]
> Is the idea that I'll have to push additional commits to robot's migration PR?

Yes. Would you like to be added as a maintainer here? That would give you push permissions for the bot branch.

**Comment by andrey-khropov** [comment]
> Would you like to be added as a maintainer here? That would give you push permissions for the bot branch.

Yes. That would be logical as I am a maintainer of CatBoost itself.

**Comment by mfansler** [comment]
resolved with #72

**Pull request closed without merging**
