### PR TITLE
Re-render, R3.5, update version to 0.10.4

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
Two wrong build requirements are installed for the windows builds:

R3.5.1 (r-git2r and r-openssl are wrong):
    r-base:                  3.5.1-h8933c1f_0        conda-forge
    r-curl:                  3.2-r351h6115d3f_2      conda-forge
    r-devtools:              1.13.6-r351h6115d3f_1   conda-forge
    r-digest:                0.6.16-r351h6115d3f_1   conda-forge
    r-git2r:                 0.20.0-mro343h889e2dd_0 defaults   
    r-httr:                  1.3.1-r351h6115d3f_1    conda-forge
    r-jsonlite:              1.5-r351h6115d3f_2      conda-forge
    r-memoise:               1.1.0-r351h6115d3f_1    conda-forge
    r-mime:                  0.5-r351h6115d3f_2      conda-forge
    r-openssl:               0.9.9-mro343h889e2dd_0  defaults   
    r-r6:                    2.2.2-r351h6115d3f_1    conda-forge
    r-rstudioapi:            0.7-r351h6115d3f_1      conda-forge
    r-whisker:               0.3_2-r351h6115d3f_1    conda-forge
    r-withr:                 2.1.2-r351h6115d3f_0    conda-forge

R3.4.1 (not failing but still wrong r-openssl package):
    r-base:                  3.4.1-h8933c1f_8       conda-forge
    r-curl:                  3.2-r341h6115d3f_2     conda-forge
    r-devtools:              1.13.6-r341h6115d3f_1  conda-forge
    r-digest:                0.6.16-r341h6115d3f_1  conda-forge
    r-git2r:                 0.19.0-r3.4.1_0        conda-forge
    r-httr:                  1.3.1-r341h6115d3f_1   conda-forge
    r-jsonlite:              1.5-r341h6115d3f_2     conda-forge
    r-memoise:               1.1.0-r341h6115d3f_1   conda-forge
    r-mime:                  0.5-r341h6115d3f_2     conda-forge
    r-openssl:               0.9.9-mro343h889e2dd_0 defaults   
    r-r6:                    2.2.2-r341h6115d3f_1   conda-forge
    r-rstudioapi:            0.7-r341h6115d3f_1     conda-forge
    r-whisker:               0.3_2-r341h6115d3f_1   conda-forge
    r-withr:                 2.1.2-r341h6115d3f_0   conda-forge

Maybe those are the cause of the failing build. The linux and osx builds install the right versions.

Why does this happen? Do some packages have corrupted package meta data or are some packages in specific version not built and uploaded?

**Comment by jdblischak** [comment]
The passing build installs m2w64-openssl, but not the failing build:

https://ci.appveyor.com/project/conda-forge/r-catboost-feedstock/build/1.0.6/job/f3ot5s1o5lte6ou6#L270

Thus maybe we need to update the r-openssl recipe to depend on `{native}openssl` instead of `openssl`:

https://github.com/conda-forge/r-openssl-feedstock/blob/master/recipe/meta.yaml#L42

**Comment by dbast** [comment]
Good point. Didn't see that. openssl seems to be part of the problem here. But the why, is not 100% clear to me yet.

**Comment by dbast** [comment]
Disabled the win-64 R3.5 build for now.

**Pull request merged**
