### PR TITLE
workaround for installing universal binaries on macos

### PR DESCRIPTION
**Pull request by Evgueni-Petrov-aka-espetrov**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@conda-forge-admin, please rerender

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
I updated version and sha256's to check that PR works for universal binaries...

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
dear @curious-odd-man could you please approve this change (or provide your feedback) so that we could publish catboost 1.0.5 with m1 support on conda ?

**Review by curious-odd-man — APPROVED** [review]
Approving, though honestly I cannot review this. Hope that everything works

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
> Approving, though honestly I cannot review this. Hope that everything works
many thanks! so we wait for conda-forge/r?

**Comment by curious-odd-man** [comment]
I've merged that. Have fun 😊

**Pull request merged**
